# Generated by Django 5.0.4 on 2024-04-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bugreport",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="priority",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="featurerequest",
            name="priority",
            field=models.IntegerField(default=1),
        ),
    ]
